# F¸r schwache Hardware
#quarkus.devservices.timeout=5m

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=nachbar
quarkus.datasource.password=nachbar
%dev.quarkus.hibernate-orm.schema-management.strategy=drop-and-create
%test.quarkus.hibernate-orm.schema-management.strategy=drop-and-create
quarkus.hibernate-orm.log.sql=true
quarkus.datasource.devservices.image-name=postgis/postgis:16-3.4
quarkus.swagger-ui.always-include=true

# File Handler
quarkus.log.file.enabled=true
quarkus.log.file.level=TRACE
quarkus.log.file.path=logs/nachbarschaftsportal.log
quarkus.log.file.format=%d{yyyy-MM-dd HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n

# containers
#quarkus.datasource.devservices.container-name=nachbar-postgres
#quarkus.keycloak.devservices.container-name=nachbar-keycloak
quarkus.datasource.devservices.port=5432
%test.quarkus.datasource.devservices.port=0


quarkus.keycloak.devservices.enabled=true
quarkus.keycloak.devservices.port=8081
#random port f¸r tests continuation im dev mode
%test.quarkus.keycloak.devservices.port=0 
quarkus.keycloak.devservices.realm-path=keycloak_realm.json
%test.quarkus.oidc.application-type=hybrid


#quarkus.oidc.auth-server-url=http://localhost:8081/realms/swa_2026 // -> darf scheinbar bei verwendung der dev Services nicht explizit zugewiesen werden, sonst l√§ufts gegen die Wand
quarkus.oidc.client-id=nachbarschaftsportal
quarkus.oidc.credentials.secret=**********
quarkus.oidc.application-type=hybrid
quarkus.oidc.roles.role-claim-path=resource_access/nachbarschaftsportal/roles
quarkus.oidc.roles.source=accesstoken
quarkus.oidc.logout.path=/logout
quarkus.oidc.logout.post-logout-path=/login

quarkus.swagger-ui.oauth-client-id=nachbarschaftsportal
